// DNS Manager API (v1)
//
// This gRPC definition provides a minimal interface for managing the
// system's DNS servers. It is written to match the exercise described
// in TASK.md (see repository root). The server-side implementation is
// expected to apply changes to /etc/resolv.conf and validate input.
// Authentication is intentionally omitted per the task requirements.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dns/v1/dns.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddDNSServerRequest carries a single DNS server address. Use a
// standard textual representation (IPv4/IPv6). The server should
// validate syntax and reject malformed addresses.
type AddDNSServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // textual IP, e.g. "192.0.2.53" or "2001:db8::53"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDNSServerRequest) Reset() {
	*x = AddDNSServerRequest{}
	mi := &file_proto_dns_v1_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDNSServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDNSServerRequest) ProtoMessage() {}

func (x *AddDNSServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dns_v1_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDNSServerRequest.ProtoReflect.Descriptor instead.
func (*AddDNSServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_dns_v1_dns_proto_rawDescGZIP(), []int{0}
}

func (x *AddDNSServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RemoveDNSServerRequest identifies a DNS server address to remove.
type RemoveDNSServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // must match an existing entry to be removed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDNSServerRequest) Reset() {
	*x = RemoveDNSServerRequest{}
	mi := &file_proto_dns_v1_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDNSServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDNSServerRequest) ProtoMessage() {}

func (x *RemoveDNSServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dns_v1_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDNSServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveDNSServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_dns_v1_dns_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveDNSServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// ListDNSServersResponse contains the ordered list of resolver
// addresses. The order should reflect the order they appear in
// /etc/resolv.conf.
type ListDNSServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"` // ordered list of nameserver addresses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDNSServersResponse) Reset() {
	*x = ListDNSServersResponse{}
	mi := &file_proto_dns_v1_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDNSServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDNSServersResponse) ProtoMessage() {}

func (x *ListDNSServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dns_v1_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDNSServersResponse.ProtoReflect.Descriptor instead.
func (*ListDNSServersResponse) Descriptor() ([]byte, []int) {
	return file_proto_dns_v1_dns_proto_rawDescGZIP(), []int{2}
}

func (x *ListDNSServersResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_proto_dns_v1_dns_proto protoreflect.FileDescriptor

const file_proto_dns_v1_dns_proto_rawDesc = "" +
	"\n" +
	"\x16proto/dns/v1/dns.proto\x12\x06dns.v1\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x13AddDNSServerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"2\n" +
	"\x16RemoveDNSServerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"6\n" +
	"\x16ListDNSServersResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses2\xe6\x01\n" +
	"\n" +
	"DNSManager\x12C\n" +
	"\fAddDNSServer\x12\x1b.dns.v1.AddDNSServerRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0fRemoveDNSServer\x12\x1e.dns.v1.RemoveDNSServerRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0eListDNSServers\x12\x16.google.protobuf.Empty\x1a\x1e.dns.v1.ListDNSServersResponseB1Z/github.com/ilindan-dev/dns-manager/proto/dns/v1b\x06proto3"

var (
	file_proto_dns_v1_dns_proto_rawDescOnce sync.Once
	file_proto_dns_v1_dns_proto_rawDescData []byte
)

func file_proto_dns_v1_dns_proto_rawDescGZIP() []byte {
	file_proto_dns_v1_dns_proto_rawDescOnce.Do(func() {
		file_proto_dns_v1_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dns_v1_dns_proto_rawDesc), len(file_proto_dns_v1_dns_proto_rawDesc)))
	})
	return file_proto_dns_v1_dns_proto_rawDescData
}

var file_proto_dns_v1_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_dns_v1_dns_proto_goTypes = []any{
	(*AddDNSServerRequest)(nil),    // 0: dns.v1.AddDNSServerRequest
	(*RemoveDNSServerRequest)(nil), // 1: dns.v1.RemoveDNSServerRequest
	(*ListDNSServersResponse)(nil), // 2: dns.v1.ListDNSServersResponse
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_proto_dns_v1_dns_proto_depIdxs = []int32{
	0, // 0: dns.v1.DNSManager.AddDNSServer:input_type -> dns.v1.AddDNSServerRequest
	1, // 1: dns.v1.DNSManager.RemoveDNSServer:input_type -> dns.v1.RemoveDNSServerRequest
	3, // 2: dns.v1.DNSManager.ListDNSServers:input_type -> google.protobuf.Empty
	3, // 3: dns.v1.DNSManager.AddDNSServer:output_type -> google.protobuf.Empty
	3, // 4: dns.v1.DNSManager.RemoveDNSServer:output_type -> google.protobuf.Empty
	2, // 5: dns.v1.DNSManager.ListDNSServers:output_type -> dns.v1.ListDNSServersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dns_v1_dns_proto_init() }
func file_proto_dns_v1_dns_proto_init() {
	if File_proto_dns_v1_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dns_v1_dns_proto_rawDesc), len(file_proto_dns_v1_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dns_v1_dns_proto_goTypes,
		DependencyIndexes: file_proto_dns_v1_dns_proto_depIdxs,
		MessageInfos:      file_proto_dns_v1_dns_proto_msgTypes,
	}.Build()
	File_proto_dns_v1_dns_proto = out.File
	file_proto_dns_v1_dns_proto_goTypes = nil
	file_proto_dns_v1_dns_proto_depIdxs = nil
}
