// DNS Manager API (v1)
//
// This gRPC definition provides a minimal interface for managing the
// system's DNS servers. It is written to match the exercise described
// in TASK.md (see repository root). The server-side implementation is
// expected to apply changes to /etc/resolv.conf and validate input.
// Authentication is intentionally omitted per the task requirements.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/dns/v1/dns.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DNSManager_AddDNSServer_FullMethodName    = "/dns.v1.DNSManager/AddDNSServer"
	DNSManager_RemoveDNSServer_FullMethodName = "/dns.v1.DNSManager/RemoveDNSServer"
	DNSManager_ListDNSServers_FullMethodName  = "/dns.v1.DNSManager/ListDNSServers"
)

// DNSManagerClient is the client API for DNSManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DNSManager exposes simple operations to add, remove and list DNS
// server addresses. The service assumes the server process will
// translate these RPCs into updates to /etc/resolv.conf and handle
// invalid input gracefully.
type DNSManagerClient interface {
	// AddDNSServer adds a single DNS server address (typically an IP
	// like "8.8.8.8") to the system resolver configuration. The server
	// must validate the address format and return an error for invalid
	// values. No payload is returned on success (google.protobuf.Empty).
	AddDNSServer(ctx context.Context, in *AddDNSServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RemoveDNSServer removes the given DNS server address from the
	// resolver configuration. If the address is not present, the server
	// should return a clear, recoverable error.
	RemoveDNSServer(ctx context.Context, in *RemoveDNSServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListDNSServers returns the currently configured resolver addresses.
	// This maps directly to the lines in /etc/resolv.conf that specify
	// "nameserver" entries.
	ListDNSServers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDNSServersResponse, error)
}

type dNSManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSManagerClient(cc grpc.ClientConnInterface) DNSManagerClient {
	return &dNSManagerClient{cc}
}

func (c *dNSManagerClient) AddDNSServer(ctx context.Context, in *AddDNSServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DNSManager_AddDNSServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSManagerClient) RemoveDNSServer(ctx context.Context, in *RemoveDNSServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DNSManager_RemoveDNSServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSManagerClient) ListDNSServers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDNSServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDNSServersResponse)
	err := c.cc.Invoke(ctx, DNSManager_ListDNSServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSManagerServer is the server API for DNSManager service.
// All implementations must embed UnimplementedDNSManagerServer
// for forward compatibility.
//
// DNSManager exposes simple operations to add, remove and list DNS
// server addresses. The service assumes the server process will
// translate these RPCs into updates to /etc/resolv.conf and handle
// invalid input gracefully.
type DNSManagerServer interface {
	// AddDNSServer adds a single DNS server address (typically an IP
	// like "8.8.8.8") to the system resolver configuration. The server
	// must validate the address format and return an error for invalid
	// values. No payload is returned on success (google.protobuf.Empty).
	AddDNSServer(context.Context, *AddDNSServerRequest) (*emptypb.Empty, error)
	// RemoveDNSServer removes the given DNS server address from the
	// resolver configuration. If the address is not present, the server
	// should return a clear, recoverable error.
	RemoveDNSServer(context.Context, *RemoveDNSServerRequest) (*emptypb.Empty, error)
	// ListDNSServers returns the currently configured resolver addresses.
	// This maps directly to the lines in /etc/resolv.conf that specify
	// "nameserver" entries.
	ListDNSServers(context.Context, *emptypb.Empty) (*ListDNSServersResponse, error)
	mustEmbedUnimplementedDNSManagerServer()
}

// UnimplementedDNSManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSManagerServer struct{}

func (UnimplementedDNSManagerServer) AddDNSServer(context.Context, *AddDNSServerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDNSServer not implemented")
}
func (UnimplementedDNSManagerServer) RemoveDNSServer(context.Context, *RemoveDNSServerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDNSServer not implemented")
}
func (UnimplementedDNSManagerServer) ListDNSServers(context.Context, *emptypb.Empty) (*ListDNSServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDNSServers not implemented")
}
func (UnimplementedDNSManagerServer) mustEmbedUnimplementedDNSManagerServer() {}
func (UnimplementedDNSManagerServer) testEmbeddedByValue()                    {}

// UnsafeDNSManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSManagerServer will
// result in compilation errors.
type UnsafeDNSManagerServer interface {
	mustEmbedUnimplementedDNSManagerServer()
}

func RegisterDNSManagerServer(s grpc.ServiceRegistrar, srv DNSManagerServer) {
	// If the following call panics, it indicates UnimplementedDNSManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSManager_ServiceDesc, srv)
}

func _DNSManager_AddDNSServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDNSServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSManagerServer).AddDNSServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSManager_AddDNSServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSManagerServer).AddDNSServer(ctx, req.(*AddDNSServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSManager_RemoveDNSServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDNSServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSManagerServer).RemoveDNSServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSManager_RemoveDNSServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSManagerServer).RemoveDNSServer(ctx, req.(*RemoveDNSServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSManager_ListDNSServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSManagerServer).ListDNSServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSManager_ListDNSServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSManagerServer).ListDNSServers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSManager_ServiceDesc is the grpc.ServiceDesc for DNSManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.v1.DNSManager",
	HandlerType: (*DNSManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDNSServer",
			Handler:    _DNSManager_AddDNSServer_Handler,
		},
		{
			MethodName: "RemoveDNSServer",
			Handler:    _DNSManager_RemoveDNSServer_Handler,
		},
		{
			MethodName: "ListDNSServers",
			Handler:    _DNSManager_ListDNSServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dns/v1/dns.proto",
}
